services:
  postgres:
    image: postgres:16
    container_name: vacation_budget_db
    environment:
      POSTGRES_USER: vacation
      POSTGRES_PASSWORD: vacation
      POSTGRES_DB: vacation_budget
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
